// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyueczxfetihhqhesknu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5dWVjenhmZXRpaGhxaGVza251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDQ5NzgsImV4cCI6MjA2NDEyMDk3OH0.4ULPEYsrV2XoPXBR5_KU-OmqbSgnw5ksRC0aDLzfQ78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);